import { MigrationInterface, QueryRunner } from "typeorm";

export class mysqlTables1685614646067 implements MigrationInterface {
    name = 'mysqlTables1685614646067'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`module_web3_wallet_configs\` (\`name\` text NOT NULL, \`value\` text NOT NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isArchived\` tinyint NOT NULL DEFAULT 0, \`createDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`createdBy\` varchar(300) NULL, \`lastChangedDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6), \`lastChangedBy\` varchar(300) NULL, \`internalComment\` varchar(300) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`module_web3_wallet_users\` (\`account_address\` text NOT NULL, \`encrypted\` text NOT NULL, \`status\` text NOT NULL DEFAULT 'pending', \`password\` text NULL, \`role\` text NULL DEFAULT 'user', \`_id\` text NULL, \`nonce\` int NULL, \`wallet_address\` text NULL, \`total_usdt_balance\` float NOT NULL DEFAULT '0', \`id\` int NOT NULL AUTO_INCREMENT, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isArchived\` tinyint NOT NULL DEFAULT 0, \`createDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`createdBy\` varchar(300) NULL, \`lastChangedDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6), \`lastChangedBy\` varchar(300) NULL, \`internalComment\` varchar(300) NULL, UNIQUE INDEX \`IDX_0a2403c4e56d3fb02b2271ca42\` (\`account_address\`), UNIQUE INDEX \`IDX_bed3d0a9c8a1989953e5d17274\` (\`_id\`), UNIQUE INDEX \`IDX_b3e47cd93e030fc37141c6e316\` (\`wallet_address\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`module_web3_wallet_nft_airdrop_daily_report\` (\`account_address\` text NOT NULL, \`totalNFTs\` int NOT NULL, \`tokens\` int NOT NULL, \`claimedBefore\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`status\` text NOT NULL DEFAULT 'pending', \`unique_key\` text NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isArchived\` tinyint NOT NULL DEFAULT 0, \`createDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`createdBy\` varchar(300) NULL, \`lastChangedDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6), \`lastChangedBy\` varchar(300) NULL, \`internalComment\` varchar(300) NULL, \`userId\` int NULL, UNIQUE INDEX \`IDX_48c3dd5f7336cf544eef85306c\` (\`unique_key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`module_web3_wallet_token_transactions\` (\`transaction_hash\` text NOT NULL, \`from_address\` text NOT NULL, \`to_address\` text NOT NULL, \`block_number\` text NOT NULL, \`value\` text NOT NULL, \`status\` text NOT NULL DEFAULT 'received', \`transaction_hash_matic\` text NULL, \`transaction_hash_deposit\` text NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isArchived\` tinyint NOT NULL DEFAULT 0, \`createDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`createdBy\` varchar(300) NULL, \`lastChangedDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6), \`lastChangedBy\` varchar(300) NULL, \`internalComment\` varchar(300) NULL, UNIQUE INDEX \`IDX_0b9da02860b8f1c312b41e6754\` (\`transaction_hash\`), UNIQUE INDEX \`IDX_8c4e08802a4431f66ad47ef03c\` (\`transaction_hash_matic\`), UNIQUE INDEX \`IDX_5132a9f2ce4fc3a663b606cc60\` (\`transaction_hash_deposit\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`module_web3_wallet_transactions\` (\`amount\` float NOT NULL, \`systemFee\` float NULL DEFAULT '0', \`account_address\` text NOT NULL, \`operation\` text NOT NULL, \`operation_details\` text NULL, \`description\` text NULL, \`blockchain_tx_id\` text NULL, \`status\` text NOT NULL DEFAULT 'pending', \`to_account_address\` text NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isArchived\` tinyint NOT NULL DEFAULT 0, \`createDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`createdBy\` varchar(300) NULL, \`lastChangedDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6), \`lastChangedBy\` varchar(300) NULL, \`internalComment\` varchar(300) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`web3_wallet_usdt_transactions\` (\`amount\` float NOT NULL, \`systemFee\` float NULL DEFAULT '0', \`account_address\` text NOT NULL, \`operation\` text NOT NULL, \`operation_details\` text NULL, \`description\` text NULL, \`blockchain_tx_id\` text NULL, \`status\` text NOT NULL DEFAULT 'pending', \`to_account_address\` text NULL, \`transaction_hash_matic\` text NULL, \`transaction_hash_deposit\` text NULL, \`transaction_hash\` text NOT NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isArchived\` tinyint NOT NULL DEFAULT 0, \`createDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`createdBy\` varchar(300) NULL, \`lastChangedDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6), \`lastChangedBy\` varchar(300) NULL, \`internalComment\` varchar(300) NULL, UNIQUE INDEX \`IDX_53cc794bdcf7b89656d0ecca7b\` (\`transaction_hash_matic\`), UNIQUE INDEX \`IDX_463d8885670e4b79ca11e052d5\` (\`transaction_hash_deposit\`), UNIQUE INDEX \`IDX_7f0dc1289f9135383034b3627c\` (\`transaction_hash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`module_web3_wallet_withdraw_requests\` (\`amount\` float NOT NULL, \`account_address\` text NOT NULL, \`description\` text NULL, \`blockchain_tx_id\` text NULL, \`status\` text NOT NULL DEFAULT 'pending', \`id\` int NOT NULL AUTO_INCREMENT, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isArchived\` tinyint NOT NULL DEFAULT 0, \`createDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`createdBy\` varchar(300) NULL, \`lastChangedDateTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6), \`lastChangedBy\` varchar(300) NULL, \`internalComment\` varchar(300) NULL, \`transactionId\` int NULL, UNIQUE INDEX \`REL_338d1d0aad459ce7eec1953fa3\` (\`transactionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`module_web3_wallet_nft_airdrop_daily_report\` ADD CONSTRAINT \`FK_7e2b4c67985b1e856998c57aa33\` FOREIGN KEY (\`userId\`) REFERENCES \`module_web3_wallet_users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`module_web3_wallet_withdraw_requests\` ADD CONSTRAINT \`FK_338d1d0aad459ce7eec1953fa36\` FOREIGN KEY (\`transactionId\`) REFERENCES \`module_web3_wallet_transactions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`module_web3_wallet_withdraw_requests\` DROP FOREIGN KEY \`FK_338d1d0aad459ce7eec1953fa36\``);
        await queryRunner.query(`ALTER TABLE \`module_web3_wallet_nft_airdrop_daily_report\` DROP FOREIGN KEY \`FK_7e2b4c67985b1e856998c57aa33\``);
        await queryRunner.query(`DROP INDEX \`REL_338d1d0aad459ce7eec1953fa3\` ON \`module_web3_wallet_withdraw_requests\``);
        await queryRunner.query(`DROP TABLE \`module_web3_wallet_withdraw_requests\``);
        await queryRunner.query(`DROP INDEX \`IDX_7f0dc1289f9135383034b3627c\` ON \`web3_wallet_usdt_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_463d8885670e4b79ca11e052d5\` ON \`web3_wallet_usdt_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_53cc794bdcf7b89656d0ecca7b\` ON \`web3_wallet_usdt_transactions\``);
        await queryRunner.query(`DROP TABLE \`web3_wallet_usdt_transactions\``);
        await queryRunner.query(`DROP TABLE \`module_web3_wallet_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_5132a9f2ce4fc3a663b606cc60\` ON \`module_web3_wallet_token_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_8c4e08802a4431f66ad47ef03c\` ON \`module_web3_wallet_token_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_0b9da02860b8f1c312b41e6754\` ON \`module_web3_wallet_token_transactions\``);
        await queryRunner.query(`DROP TABLE \`module_web3_wallet_token_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_48c3dd5f7336cf544eef85306c\` ON \`module_web3_wallet_nft_airdrop_daily_report\``);
        await queryRunner.query(`DROP TABLE \`module_web3_wallet_nft_airdrop_daily_report\``);
        await queryRunner.query(`DROP INDEX \`IDX_b3e47cd93e030fc37141c6e316\` ON \`module_web3_wallet_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_bed3d0a9c8a1989953e5d17274\` ON \`module_web3_wallet_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_0a2403c4e56d3fb02b2271ca42\` ON \`module_web3_wallet_users\``);
        await queryRunner.query(`DROP TABLE \`module_web3_wallet_users\``);
        await queryRunner.query(`DROP TABLE \`module_web3_wallet_configs\``);
    }

}
